# Generated by Django 4.1.13 on 2024-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=350)),
                ('address', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
