# Generated by Django 4.2.3 on 2023-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_content_departmenttask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='additional_description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
