# Generated by Django 4.1.13 on 2024-02-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='job_position',
            new_name='employer',
        ),
    ]
