# Generated by Django 4.1.13 on 2024-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='position',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='department',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
