# Generated by Django 4.1.13 on 2023-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_additional_description'),
        ('dashboard', '__first__'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='graph_permission',
            field=models.ManyToManyField(default=None, to='dashboard.graphpermission'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='insights_permission',
            field=models.ManyToManyField(default=None, to='dashboard.graphinsights'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='lead',
            field=models.ManyToManyField(default=None, to='tasks.lead'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='task',
            field=models.ManyToManyField(default=None, to='tasks.task'),
        ),
    ]
