# Generated by Django 4.1.13 on 2024-02-04 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0002_rename_position_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='costumer_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='costumer_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='title',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='ben@ben.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='first name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('lost', 'Lost'), ('converted', 'Converted')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='employer',
            name='lead',
        ),
        migrations.AddField(
            model_name='employer',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employer.lead'),
        ),
    ]
