# Generated by Django 4.1.13 on 2024-02-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_rename_job_position_employer_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='employer',
            new_name='department',
        ),
    ]
