# Generated by Django 4.1.13 on 2024-02-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_lead_completed_remove_lead_costumer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='employer.employer'),
        ),
    ]
