# Generated by Django 4.1.13 on 2024-02-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('employer', '0004_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finance.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
