# Generated by Django 4.2.3 on 2023-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_departmenttask_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmenttask',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='departmenttask',
            name='additional_description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='costumer_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='costumer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='additional_description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
