# Generated by Django 4.1.13 on 2024-01-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='costumer_id',
            new_name='customer_id',
        ),
    ]
