# Generated by Django 4.1.13 on 2024-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='date_time',
        ),
        migrations.AddField(
            model_name='outcome',
            name='date_received',
            field=models.DateField(default='2027-01-01'),
            preserve_default=False,
        ),
    ]
