# Generated by Django 4.1.13 on 2024-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_outcome_date_time_outcome_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
    ]
