# Generated by Django 4.1.13 on 2024-03-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0004_alter_income_company_alter_income_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='income',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finance.customer'),
        ),
    ]
