# Generated by Django 4.1.13 on 2024-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_income_company_alter_income_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date_received',
            field=models.DateField(),
        ),
    ]
