# Generated by Django 4.1.13 on 2024-03-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_name_customer_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='name',
        ),
    ]
